name: .NET

on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: publish win
      run: dotnet publish -c Release -r win-x64 --no-self-contained
    - name: publish ubuntu
      run: dotnet publish -c Release -r ubuntu-x64 --no-self-contained
    - name: publish mac
      run: dotnet publish -c Release -r osx-x64 --no-self-contained
    - name: install zip
      run: sudo apt install zip
    - name: zip win
      run: zip -r Tobi-windows.zip DiscordBot/bin/Release/net7.0/win-x64/publish
    - name: zip mac
      run: zip -r Tobi-mac.zip DiscordBot/bin/Release/net7.0/osx-x64/publish
    - name: zip ubuntu
      run: zip -r Tobi-ubuntu.zip DiscordBot/bin/Release/net7.0/ubuntu-x64/publish
    
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Tobi-windows.zip
          Tobi-mac.zip
          Tobi-ubuntu.zip
